<a href="https://colab.research.google.com/github/JuandaJimenezGuerra/fundamentos-de-programacion/blob/main/prueba_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Ejercicio 1** (50 pts)

Escriba una clase `Pedido` que pueda ser usada para gestionar la información de los pedidos realizados a una pastelería (o carnicería o tienda de ropa o empresa que ud desee). Evite usar módulos como numpy, pandas o cualquier otro.

### **Rubrica**:

1. Generación de la clase que funcione correctamente con al menos 2 métodos y 2 atributos. **30 pts**.
2. Comentarios y  documentación que sirva para quien deba usar la clase. **5 pts**.
3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio? esta será entregada en una celda de texto. **10 pts**.
4. ¿Cree que se pueda construir una clase hija que ayude al proceso? Si sí constrúyala, sino, argumente por qué en una célda de código. **5 pts**.

In [ ]:
#clase generica de un pedido

class Pedido():
  compras = []
  def __init__(self, id_cliente: int, id_factura: int, descuento: float):
    """
      Inicializa un nuevo pedido con los detalles especificados.

      Atributos de la clase:
      - id_cliente (int): El identificador del cliente.
      - id_factura (int): El número de la factura asociada al pedido.
      - descuento (float): El porcentaje de descuento aplicable al pedido.
      - articulos (dict): Un diccionario que almacena los artículos disponibles para compra, donde cada artículo es identificado por un ID único.
    """

    self.info = {
        "Cliente": id_cliente,
        "Número de Factura": id_factura,
        "% Descuento": descuento
        }
    self.articulos = {
    1:{
        "id":1,
        "nombre": "camiseta",
        "precio": 25000,
        "cantidad_disponible": 100
    },
    2:{
        "id":2,
        "nombre": "pantalon",
        "precio": 50000,
        "cantidad_disponible": 80
    },
    3:{
        "id":3,
        "nombre": "saco",
        "precio": 75000,
        "cantidad_disponible": 120
    },
    }

  #Método que permite listar los articulos disponibles en la tienda

  def listar_articulos(self):
    """
      Imprime una lista de los artículos y cantidades disponibles en la tienda.
      Esta función recorre todos los artículos almacenados en el diccionario "articulos" y los imprime.
      Cada artículo se muestra con su ID, nombre, precio y cantidad disponible.

      Ejemplo de salida:
        {'id': 1, 'nombre': 'camiseta', 'precio': 25000, 'cantidad_disponible': 100}
    """
    for id in self.articulos:
      print(self.articulos[id])


  #Método que le permite al empleado de la tienda agregar artículos al pedido de un cliente

  def agregar_articulo(self, id_articulo: int, cantidad: int):
    """
      Esta función permite añadir un nuevo artículo a la lista de compras de un cliente,
      actualizando la cantidad disponible del artículo.
      Cada artículo agregado se registra mediante su ID y la cantidad deseada.

      Parámetros:
      - id_articulo (int): El identificador único del artículo a agregar.
      - cantidad (int): La cantidad del artículo que se desea agregar al pedido.
   """
    if id_articulo not in self.articulos:
      print("Artículo no encontrado. Por favor, ingrese un ID de artículo válido.")
      return
    if cantidad > self.articulos[id_articulo]["cantidad_disponible"]:
      print("Cantidad no disponible. Por favor, ingrese una cantidad válida.")
    else:
      self.compras.append((id_articulo, cantidad))

      # Actualiza la cantidad disponible del artículo.
      self.articulos[id_articulo]["cantidad_disponible"]-= cantidad



  #Método que calcula el total del pedido del cliente

  def calcular_total_pedido(self):
    """
      Esta función recorre la lista de compras del pedido, identifica cada artículo por su ID y utiliza su precio
      (obtenido del diccionario de artículos) para calcular el total del pedido.

      Retorna:
      - float: El total del pedido calculado a partir de los precios de los artículos y sus cantidades.
    """
    suma = 0
    for (id_articulo,cantidad) in self.compras:
      articulo = self.articulos[id_articulo]
      precio = articulo["precio"]
      suma += cantidad * precio
    return suma



  #Método que imprime el resumen del pedido

  def resumen_compra(self):
    """
      Imprime un resumen de la compra, incluyendo el total antes y después de aplicar descuentos.
      El descuento se aplica sobre el total del pedido y el nuevo total se calcula descontando el porcentaje especificado en "info["% Descuento"]".

      Este método no retorna ningún valor, su propósito es únicamente informativo, imprimiendo el resumen en consola.
    """

    total_pedido = self.calcular_total_pedido()
    print(f"""
    ***** Resumen de la compra *****
    Id Cliente:                 {self.info["Cliente"]}
    Factura Número:             {self.info["Número de Factura"]}
    Total antes de descuentos: ${total_pedido}
    Total con descuentos:      ${total_pedido*(1-self.info["% Descuento"])}
    """)


#Clase hija de Pedido, que representa un pedido destinado a envío:
#Se construye esta clase hija para gestionar pedidos que requieren entrega a domicilio,facilitando agregar detalles del envío.

class Pedido_para_enviar(Pedido):
  def __init__(self, id_cliente: int, id_factura: int, descuento: float, direccion: str, telefono: str):
    """
      Esta clase añade atributos específicos para manejar la información necesaria para
      realizar el envío del pedido, como la dirección y el teléfono del cliente.

      Atributos añadidos:
        - direccion (str): Dirección de envío del pedido.
        - telefono (str): Número de teléfono de contacto del cliente.
      """
    Pedido.__init__(self, id_cliente, id_factura, descuento)
    self.info['Dirección'] = direccion
    self.info['Teléfono'] = telefono


In [ ]:
#Prueba funcionamiento clase Pedido:
pedido1 = Pedido(id_cliente=34, id_factura=1, descuento=0.1)
pedido1.listar_articulos()
pedido1.agregar_articulo(1,4)
pedido1.agregar_articulo(3,1)
pedido1.calcular_total_pedido()
pedido1.resumen_compra()

In [ ]:
#Prueba funcionamiento clase Pedido_para_enviar:
pedido2 = Pedido_para_enviar(id_cliente=34, id_factura=1, descuento=0.1, direccion= "xx", telefono="yy")
pedido2.info

**3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio?:**
La clase ***'Pedido'***, le permitirá a las personas encargadas en la tienda de ropas gestionar adecuadamente los pedidos de sus clientes. La herramienta automatiza varios procesos asociados con la venta de artículos, le permitirá a los empleados revisar el inventario disponible, ingresar al sistema las cantidades vendidas por artículo y calcular el total que debe ser cobrado al cliente. En caso de existir algún descuento podrá ser ingresado al sistema y el valor total con descuento será visible para el empleado en el resumen de la compra.

Esto agiliza el proceso de pedidos en la tienda, permitiéndo a los empleados acelerar el proceso y enfocarse en tareas más importantes o que generen valor.

Además, para pedidos a domicilio, la plataforma captura automáticamente la dirección y teléfono del cliente, garantizando que el equipo de envíos disponga de toda la información necesaria para la entrega.

## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **16 pts**

$$
2x + 3y - z + 4w + 5v = 15
$$

$$
x - 2y + 4z - 3w + v = 6
$$

$$
3x + 2y - 3z + 5w - 2v = 11
$$

$$
4x + y - 2z + 3w + 2v = 8
$$

$$
x + y + z + w + v = 7
$$

2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:

$$e = \sum_i ^{\infty} \frac{1}{n!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **18 pts**

3. Ecuentre los auto valores de la matriz.  **16 pts**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$


**SOLUCION 2.1**

In [ ]:
"""
Este calculo resuelve un sistema de ecuaciones lineales representado por una matriz y un vector. Luego, imprime los valores de
las incógnitas y verifica que estos valores satisfagan las ecuaciones originales.
"""

#Primero que todo importamos la librería que vamos a necesitar
import numpy as np

#Llevamos a una matriz los coeficientes que se encuentran en el sistema de ecuaciones y creamos un vector con los resultados del sistema de ecuaciones
matriz = np.array([[2, 3, -1, 4, 5],[1, -2, 4, -3, 1],[3, 2, -3, 5, -2],[4, 1, -2, 3, 2],[1, 1, 1, 1, 1]])
vector = np.array([15,6,11,8,7])

#Guardamos dentro de una nueva variable el resultado del sistema de ecuaciones
res = np.linalg.solve(matriz, vector)

#Guardamos dentro de cada variable el valor obtenido en el sistema de ecuaciones
x = res[0]
y = res[1]
z = res[2]
w = res[3]
v = res[4]

#Exponemos el valor de las varibales incognitas
print()
print("A continuación se muestra el valor de cada variable: \n")
print(f'La variable X es: {x} \nLa variable Y es: {y} \nLa variable Z es: {z} \nLa variable W es: {w} \nLa variable V es: {v}')

#Comprobamos que el sistema de ecuaciones cumpla con las condiciones:
ec1 = (2*x) + (3*y) - z + (4*w) + (5*v)
ec2 = x - (2*y) + (4*z) - (3*w) + v
ec3 = (3*x) + (2*y) - (3*z) + (5*w) - (2*v)
ec4 = (4*x) + y - (2*z) + (3*w) + (2*v)
ec5 = x + y + z + w + v

print("\nFinalmente, se verifica que las ecuaciones cumplan los criterios\n")
print("El valor de ec1 es: ", ec1)
print("El valor de ec2 es: ", ec2)
print("El valor de ec3 es: ", ec3)
print("El valor de ec4 es: ", ec4)
print("El valor de ec5 es: ", ec5)


A continuación se muestra el valor de cada variable: 

La variable X es: -1.6774193548387097 
La variable Y es: -7.870967741935485 
La variable Z es: 5.129032258064516 
La variable W es: 10.0 
La variable V es: 1.4193548387096777

Finalmente, se verifica que las ecuaciones cumplan los criterios

El valor de ec1 es:  14.999999999999996
El valor de ec2 es:  5.999999999999998
El valor de ec3 es:  10.999999999999996
El valor de ec4 es:  8.0
El valor de ec5 es:  7.0


**SOLUCION 2.2**

In [ ]:
import numpy as np
import math

def calcular_euler(iteraciones=100):
    """
    Esta función calcula un aproximado del valor de Euler a través de una sumatoria de su fórmula base.
    Se le debe pasar como variable el número de iteraciones que se desean realizar, teniendo en cuenta
    también que dentro de su estructura hay un número factorial.

    Inicialmente se crea un array desde 0 hasta el límite de iteraciones deseado. Luego se calcula el factorial
    utilizando una función de la libreria -math-, los cuales cumpliran la función de divisor dentro de la sumatoria.

    Finalmente se realiza una sumatoria de todos los elementos guardados dentro del array conformado por la división
    de 1 entre los factoriales calculados.
    """
    # Crear un array con los valores de 0 a iteraciones-1
    n_values = np.arange(iteraciones)

    # Calcular los factoriales de los valores en n_values utilizando np.math.factorial
    factoriales = np.array([math.factorial(n) for n in n_values])

    # Calcular la serie de Euler
    euler_series = 1 / factoriales

    # Sumar los elementos de la serie para obtener el número de Euler
    euler_aproximado = np.sum(euler_series)

    return euler_aproximado

# Especificar el número de iteraciones para mayor precisión
numero_de_euler = calcular_euler(iteraciones=1000)
print(f"Número de Euler aproximado: {numero_de_euler}")

Número de Euler aproximado: 2.7182818284590455


**SOLUCION 2.3**

In [ ]:
"""
    Este calculo determina los autovalores de la matriz solicitada.
    Se expresa la matriz en un arreglo de NumPy. Finalmente, se utiliza la función np.linalg.eigvals() para calcular los
    autovalores de la matriz, que se imprimen en pantalla.

    Los autovalores representan las soluciones λ de la ecuación característica det(A - λI) = 0, donde A es la matriz, λ
    es el autovalor y I es la matriz identidad. Los autovectores de una matriz son vectores no nulos que, al ser
    multiplicados por la matriz, dan como resultado un múltiplo escalar de sí mismos, es decir, mantienen la misma dirección.
"""

# Primero que todo importamos la librería que vamos a necesitar
import numpy as np

#Llevamos la matriz a un arreglo de numpy
matriz = np.array([[2, 1, 1], [4, 3, 2], [1, 1, 2]])


# Calcular los autovalores y autovectores
autovalores, autovectores = np.linalg.eig(matriz)

#Imprimimos los resultados
print("Los autovalores de la matriz son:\n", autovalores)
print("\nLos autovalores de la matriz son:\n", autovectores)

Los autovalores de la matriz son:
 [5.44948974 0.55051026 1.        ]

Los autovalores de la matriz son:
 [[ 3.53553391e-01  3.53553391e-01  6.66133815e-16]
 [ 8.66025404e-01 -8.66025404e-01 -7.07106781e-01]
 [ 3.53553391e-01  3.53553391e-01  7.07106781e-01]]


Borrar

In [ ]:
import sympy as sp
from decimal import Decimal, getcontext
matriz_dos = sp.Matrix([[2, 1, 1], [4, 3, 2], [1, 1, 2]])
lamb_dos=sp.symbols('lambda')
sol=sp.solve(sp.det((matriz_dos-lamb_dos*sp.eye(3))))
print(sol)

[1, 3 - sqrt(6), sqrt(6) + 3]
